name: benji_vendor
description: Benji app for vendors.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http:
  cupertino_icons: ^1.0.2
  google_fonts:
  google_maps_flutter: ^2.3.1
  hexcolor: ^3.0.1
  flutter_spinkit: ^5.2.0
  flutter_pw_validator: ^1.6.0
  otp: ^3.1.4
  otp_text_field: ^1.1.3
  get: ^4.6.5
  permission_handler: ^10.3.0
  image_picker: ^1.0.7
  image_picker_for_web: ^3.0.2
  csc_picker: ^0.2.7
  intl_phone_field: ^3.2.0
  intl: ^0.18.1
  flutter_layout_grid: ^2.0.5
  liquid_pull_to_refresh: ^3.0.1
  shared_preferences: ^2.2.0
  font_awesome_flutter: ^10.5.0
  lottie:
  cached_network_image: ^3.2.3
  geolocator:
  geocoding:
  dotted_border: ^2.0.0+3
  pdf: ^3.10.4
  screenshot: ^2.1.0
  share_plus: ^7.1.0
  path_provider:
  fluttertoast:
  flutter_carousel_widget:
  readmore:
  group_radio_button:
  firebase_messaging:
  firebase_core:
  awesome_notifications:
  awesome_notifications_core:
  awesome_notifications_fcm:
  webviewx2: ^2.0.0
  stylish_bottom_bar:
  shimmer: ^3.0.0-nullsafety.0
  http_parser: ^4.0.2
  url_launcher: ^6.1.12
  webview_flutter:
  webview_flutter_android:
  webview_flutter_platform_interface:
  webview_flutter_wkwebview:
  flutter_polyline_points:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/images/logo/benji_full_logo.png
  color: "#f9f9f9"
  image_dark: assets/images/logo/benji_full_logo.png
  color_dark: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

  # flutter_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/images/logo/logo-icon.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/vendors/
    - assets/images/splash_screen/
    - assets/images/onboarding_screen/
    - assets/images/login/
    - assets/images/home/
    - assets/images/vendors/
    - assets/images/customer/
    - assets/images/products/
    - assets/icons/
    - assets/images/rider/
    - assets/images/profile/
    - assets/animations/splash_screen/
    - assets/animations/successful/
    - assets/animations/login/
    - assets/animations/signup/
    - assets/animations/payment/
    - assets/animations/no_internet/
    - assets/animations/error/
    - assets/animations/empty/
    - assets/animations/credit_card/
    - assets/animations/delivery/
    - assets/animations/google_maps/
    - assets/animations/help_and_support/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
